# This workflow aim to build and deploy the development version of PrestaShop
name: Build And Deploy Development Branch

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-deploy:
    name: Build and Deploy

    runs-on: ubuntu-latest

    env:
      PHP_VERSION: '7.4'
      NODE_VERSION: '16'
      RELEASE_DIR: '/tmp/ps-release'
      GH_BRANCH: 'develop'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.GH_BRANCH }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup NPM
        run: npm install -g npm@7

      - name: Create Release directory
        run: mkdir -p ${{ env.RELEASE_DIR }}

      - name: Create build
        run: php tools/build/CreateRelease.php --destination-dir=${{ env.RELEASE_DIR }}

      - name: Rename build
        run: mv ./*.zip ./${{ github.event.release.tag_name }}.zip
        working-directory: ${{ env.RELEASE_DIR }}

      - name: Prepare directories
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          port: ${{ secrets.PORT }}
          script: |
            rm -rf ${{ env.RELEASE_DIR }}
            mkdir -p ${{ env.RELEASE_DIR }}

      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ env.RELEASE_DIR }}/${{ github.event.release.tag_name }}.zip
          remote: ${{ env.RELEASE_DIR }}/${{ github.event.release.tag_name }}.zip
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      # https://devdocs.prestashop-project.org/1.7/basics/keeping-up-to-date/upgrade/
      - name: Overwrite files
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd ${{ env.RELEASE_DIR }}
            mkdir -p /var/www/html/prestashop
            unzip -o ${{ github.event.release.tag_name }}.zip
            unzip -o prestashop.zip
            rm -rf *zip
            rm -rf img/
            rm -rf override/
            mv ./admin $(basename $(find /var/www/html/prestashop -maxdepth 1 -type d -name "admin*"))
            rm -rf /var/www/html/prestashop/vendor/
            cp -R ./* /var/www/html/prestashop
            cd /var/www/html/prestashop
            chown -R www-data:www-data /var/www/html/prestashop/
            chmod -R 755 /var/www/html/prestashop
            rm -rf /var/www/html/prestashop/install/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.RELEASE_DIR }}/${{ github.event.release.tag_name }}.zip
