# This workflow aim to build and publish the development version of PrestaShop
name: Build Development Branch

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-publish:
    name: Build and Publish

    runs-on: ubuntu-latest

    env:
      PHP_VERSION: '7.4'
      NODE_VERSION: '16'
      RELEASE_DIR: '/tmp/ps-release'
      GH_BRANCH: 'develop'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.GH_BRANCH }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup NPM
        run: npm install -g npm@7

      - name: Create Release directory
        run: mkdir -p ${{ env.RELEASE_DIR }}

      - name: Create build
        run: php tools/build/CreateRelease.php --destination-dir=${{ env.RELEASE_DIR }}

      - name: Rename build
        run: mv ./*.zip ./${{ github.event.release.tag_name }}.zip
        working-directory: ${{ env.RELEASE_DIR }}

      - name: cleanup upload directory
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: rm -rf ${{ env.RELEASE_DIR }} && mkdir -p ${{ env.RELEASE_DIR }}

      - name: copy file to remote host
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          strip_components: 2
          source: ${{ env.RELEASE_DIR }}/${{ github.event.release.tag_name }}.zip
          target: /tmp/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.RELEASE_DIR }}/${{ github.event.release.tag_name }}.zip
